#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include: ../../_CEI-CMN/tasks/_activate.yml

- name: CEI-API | start | Activate the latest install
  install_package:
    name: ceilometer
    service: ceilometer-api
    activate: act_on
    version: "{{ ceilometer_api_install_result.version }}"
  when: ceilometer_api_activate_required

- name: CEI-API | install | Create Symlinks for  other config files from install
  file:
    src="{{ ceilometer_api_conf_dir }}/{{ item }}"
    dest="{{ ceilometer_global_conf_dir }}/{{ item }}"
    owner="{{ ceilometer_user }}"
    group="{{ ceilometer_group }}"
    state=link
  with_items:
    - api-logging.conf
    - api_paste.ini
    - ceilometer.conf
    - pipeline-api.yaml
    - policy.json
  become: yes


- name: CEI-API | start | Enable Ceilometer site
  command: a2ensite ceilometer_modwsgi

- include: "{{ playbook_dir }}/roles/FND-AP2/tasks/start_reload.yml"
  vars:
    apache_reload_requested: ceilometer_restart_required or ceilometer_api_restart_required

- name: CEI-API | start | Make sure ceilometer api is up and responding
  uri:
    url: "{{ ceilometer_api_vip_admin_url }}/v2/health"
    status_code: 200
    timeout: 20
  register: ceilometer_version_status
  until: ceilometer_version_status.status is defined and ceilometer_version_status.status == 200
  delay: 30
  retries: 6
  run_once: true
