#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: swiftlm-ring-supervisor | validate-input-model | Validate input model
  command: swiftlm-ring-supervisor
           --make-delta
           --ring-delta /tmp/tmp-ring-delta.yml
  run_once: true

- name: swiftlm-ring-supervisor | validate-input-model | Summarise changes
  command: swiftlm-ring-supervisor
           --report
           --ring-delta /tmp/tmp-ring-delta.yml
  run_once: true
  register: report

- name: swiftlm-ring-supervisor | validate-input-model | Cleanup
  file:
    path: /tmp/tmp-ring-delta.yml
    state: absent

- name: swiftlm-ring-supervisor | validate-input-model | Print report
  debug: var=report.stdout_lines