#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Start logging producer stack
- hosts: LOG-PRO
  sudo: yes
  roles:
    - { role: logging-common, tags: [ log, logpro ] }
    - { role: logging-producer, tags: [ log, logpro ] }
  tasks:
    - include: roles/logging-producer/tasks/start.yml tags=log,logpro,logprostart

# Start monitoring last as it needs other services to be already running
# Start PROducer hosts monitoring
- hosts: LOG-PRO
  sudo: yes
  roles:
    - { role: logging-common, tags: [ log, logmon ] }
    - { role: logging-monitor, tags: [ log, logmon ] }
  tasks:
    - include: roles/logging-monitor/tasks/start-PRO.yml tags=log,logmon,logmonstart,logmonstartpro
