#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
nimbus_thrift_port: 6627
storm_drpc_extra_config:
storm_local_dir: /var/storm
storm_java_library_path: "/usr/local/lib:/opt/local/lib:/usr/lib"
storm_zookeeper_port: 2181
storm_topology_extra_config:
    topology.acker.executors: 1
    topology.debug: false
storm_transactional_extra_config:
    transactional.zookeeper.port: "{{ storm_zookeeper_port }}"
    transactional.zookeeper.root: "/storm-transactional"
storm_logviewer_enabled: false  # logviewer is used by the UI
storm_ui_enabled: false
storm_ui_port: 8088
storm_version: 0.9.5
storm_zookeeper_extra_config:
    storm.zookeeper.port:  "{{ storm_zookeeper_port }}"
    storm.zookeeper.retry.interval: 5000
    storm.zookeeper.retry.times: 60
    storm.zookeeper.root: "/storm"
    storm.zookeeper.session.timeout: 3000
storm_tarball_location: /root
storm_tarball_name: apache-storm-{{storm_version}}.tar.gz

monasca_log_level: WARN
# In MB
storm_log_max_size: 100
monasca_log_rotation_backup_count: 4
monasca_wait_for_period: 60
run_mode: Deploy
skip_install: False
verify: True
storm_restart_required: False

keystone_url: "{{MON_API.consumes_KEY_API.vips.admin[0].url}}/v3"
keystone_user: "{{ MON_API.consumes_KEY_API.vars.keystone_monasca_user }}"
keystone_password: "{{ MON_API.consumes_KEY_API.vars.keystone_monasca_password | quote }}"
keystone_project: "{{KEY_API.vars.keystone_admin_tenant}}"

storm_tarball_location: "{{ monasca_jars_virtualenv_dir }}/lib"

zookeeper_nodes: "{{ MON_THR.consumes_FND_ZOO.members.private }}"
zookeeper_hosts: "{% for node in zookeeper_nodes %}{{ node.host }}:{{ node.port }}{% if not loop.last %},{% endif %}{% endfor %}"

monasca_client_venv: "{{ monasca_agent_virtualenv_dir }}"
