#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- hosts:
  - SWF-ACC
  - SWF-CON
  - SWF-OBJ
  - SWF-PRX
  roles:
  - _SWF-CMN
  tasks:
  - include: roles/_SWF-CMN/tasks/get_storage_policies_fact.yml

- hosts: SWF-PRX
  sudo: yes
  roles:
    - SWF-PRX
  tasks:
  - include: roles/SWF-PRX/tasks/configure.yml

- hosts: SWF-ACC
  sudo: yes
  roles:
  - SWF-ACC
  tasks:
  - include: roles/SWF-ACC/tasks/configure.yml

- hosts: SWF-CON
  sudo: yes
  roles:
  - SWF-CON
  tasks:
  - include: roles/SWF-CON/tasks/configure.yml

- hosts: SWF-OBJ
  sudo: yes
  roles:
  - SWF-OBJ
  tasks:
  - include: roles/SWF-OBJ/tasks/configure.yml

- hosts:
  - SWF-PRX[0]
  sudo: yes
  roles:
  - swiftlm-ring-supervisor
  tasks:
  - include: roles/swiftlm-ring-supervisor/tasks/fetch-ring-tarball.yml

- hosts:
  - SWF-ACC
  - SWF-CON
  - SWF-OBJ
  - SWF-PRX
  sudo: yes
  roles:
  - swiftlm-ring-supervisor
  tasks:
  - include: roles/swiftlm-ring-supervisor/tasks/configure.yml
  - include: roles/swiftlm-ring-supervisor/tasks/deploy-rings.yml

# Play using internal role SWF-EXP applied to the first object server
- hosts: SWF-OBJ[0]
  sudo: yes
  roles:
  - SWF-EXP
  tasks:
  - include: roles/SWF-EXP/tasks/configure.yml